allow coverage difference to be 0
neofinancial/coverage-upload-action pull request #15
Opened 2022-03-21 22:57 UTC by leah-is-offline

0 was ready as a falsey value and did not generate comment with difference. Allow difference to be 0.

2022-03-21 23:05 UTC, neo-anand-patel approved these changes

2022-03-22 01:59 UTC, AdamTranquilla submitted a review, later dismissed

2022-03-22 15:56 UTC, gate3 approved these changes

2022-03-22 20:41 UTC, PeterHuang516 approved these changes

2022-03-22 22:45 UTC, iansu requested changes
The last entry in the comment says `$0% (0%)` for some reason

2022-03-24 16:05 UTC, Shubh2022 approved these changes

2022-03-24 20:40 UTC, iansu approved these changes

2022-03-24 20:45 UTC, merged