Sc94150/update schema
neofinancial/coverage-upload-action pull request #20
Opened 2022-03-30 20:42 UTC by leah-is-offline

2022-05-11 02:59 UTC, neo-anand-patel commented
I'll do the other half of this ticket to save the `displayName` and `pathName` on [this](https://github.com/neofinancial/coverage-dashboard/pull/67) PR.

2022-05-11 16:32 UTC, AD-Blue approved these changes

2022-05-11 17:55 UTC, AdamTranquilla approved these changes
Looks good.

NIT: you could use more descriptive commit messages when addressing changes. that way if you want to revert a specific change you can identify it quickly

2022-05-13 18:08 UTC, PeterHuang516 approved these changes

2022-05-13 22:37 UTC, leah-is-offline reviewed
approve! but i can approve because it says I opened

2022-05-16 15:48 UTC, gate3 approved these changes

2022-05-17 22:57 UTC, iansu requested changes
You're going to need to update the CHANGELOG and the version in package.json. We also need to know if this is going to be a breaking change.

2022-05-17 22:57 UTC, iansu commented on src/get-data.ts
> +    pathway,
This should just be `path`

2022-05-18 18:06 UTC, closed without merging