Sc94150/update schema
neofinancial/coverage-upload-action pull request #24
Opened 2022-05-18 18:20 UTC by neo-anand-patel

### Ticket

[sc94150]

### Changes made

- modify post request to send a pathName and displayName to remote endpoint
 
### Related PRs

- In the service

### Release Plan

- half of this ticket involves work on the service that saves this data when it is received in the remote endpoint. I am planning on finishing the other half of this ticket in [sc94150] in the service.
- The plan is to merge this PR into [sc95777] and then merge [sc95777] from this repository and then [sc94150] in the service

### Checklist

- [x] Have you fully tested your PR locally

2022-05-18 18:27 UTC, neo-anand-patel commented
Old PR: https://github.com/neofinancial/coverage-upload-action/pull/20

2022-06-01 23:05 UTC, PeterHuang516 approved these changes

2022-06-02 16:07 UTC, leah-is-offline requested changes
changelog date hahaha

2022-06-02 16:44 UTC, leah-is-offline requested changes

2022-06-02 16:44 UTC, leah-is-offline commented on CHANGELOG.md
> +## 2.1.0 (April 2, 2022)
its June

2022-06-02 18:16 UTC, neo-anand-patel commented on CHANGELOG.md
> +## 2.1.0 (April 2, 2022)
That is unfortunate, thanks lol

2022-06-02 20:24 UTC, merged